[build]
command = "npm run build"
publish = "_site"


# Post deploy ping
[[plugins]]
  package = "netlify-plugin-command"
  [plugins.inputs]
    build = ""
    postBuild = "curl -s https://www.google.com/ping?sitemap=$DEPLOY_URL/sitemap.xml && curl -s https://www.bing.com/ping?sitemap=$DEPLOY_URL/sitemap.xml"
